#!/bin/bash

INSTALL_DIR=/etc/Project3
CURRENT_DIR=$(pwd)
INSTALL_FILE=udpCommands.py

DoInstall()
{
	sudo mkdir -p $INSTALL_DIR
	sudo cp $INSTALL_FILE $INSTALL_DIR
}

DoUninstall()
{
	sudo rm -rf $INSTALL_DIR
}

ShowUsage()
{
	echo '-------------------------'
	echo '------Andrew Creel-------'
	echo '------acreel@gmu.edu-----'
	echo '-------------------------'
	echo 
	echo 'Usage'
	echo 'start -Starts the contoller and UDP connection'
	echo 'stop -Stops the Program'
	echo 'install -install all the need files'
	echo 'uninstall -uninstall the files used'
}

DoStart()
{
	python $INSTALL_DIR/$INSTALL_FILE
	#screen -S $udpSend -d -m python	$INSTALL_DIR/$INSTALL_FILE_S
}

DoStop()
{
	screen -S $SCREEN_UDP -p 0 -x quit
}